-- AlterTable
ALTER TABLE "users" ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "street_address" DROP NOT NULL,
ALTER COLUMN "zip_code" DROP NOT NULL;
